
Running tests... 
----------------------------------------------------------------------
 test_png_i_b_nd_pl_fcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_i_b_nd_pl_lcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_i_nb_dc_pl_fcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_i_nb_dc_pl_lcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_i_nb_dc_pn_fcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_i_nb_dc_pn_lcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_i_nb_nd_pl_fcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_i_nb_nd_pl_lcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_i_nb_nd_pn_fcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_i_nb_nd_pn_lcl (JP_test_suite.CITPNGJPImportTests) ... SKIP (0.000000)s
 test_png_jp_payment_fi (JP_test_suite.CITPNGJPPaymentTests) ... SKIP (0.000000)s
 test_png_jp_payment_fi_3pl_access (JP_test_suite.CITPNGJPPaymentTests) ... ERROR (100.605980)s
 test_png_jp_payment_fi_rejection (JP_test_suite.CITPNGJPPaymentTests) ... SKIP (0.000000)s
 test_png_jp_payment_po (JP_test_suite.CITPNGJPPaymentTests) ... SKIP (0.000000)s
 test_png_jp_payment_po_3pl_access (JP_test_suite.CITPNGJPPaymentTests) ... ERROR (86.965933)s
 test_png_jp_payment_po_rejection (JP_test_suite.CITPNGJPPaymentTests) ... SKIP (0.000000)s
 test_png_jp_payment_po_to_fi (JP_test_suite.CITPNGJPPaymentTests) ... SKIP (0.000000)s
 test_png_jp_payment_po_to_fi_3pl_access (JP_test_suite.CITPNGJPPaymentTests) ... ERROR (91.441894)s

======================================================================
ERROR [100.605980s]: JP_test_suite.CITPNGJPPaymentTests.PNG Payment FI No change 3PL Has Access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Praca\Automation\src\JP_test_suite.py", line 1413, in test_png_jp_payment_fi_3pl_access
    orch_automation_tools.submit_main_excel(driver, self.excel_template, 'Excel Sheet Upload')
  File "C:\Praca\Automation\src\orch_automation_tools.py", line 481, in submit_main_excel
    "//td[contains(text(),'Accepted')]"
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//td[contains(text(),'Accepted')]"}
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)


======================================================================
ERROR [86.965933s]: JP_test_suite.CITPNGJPPaymentTests.PNG Payment PO no change 3PL Has Access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Praca\Automation\src\JP_test_suite.py", line 1369, in test_png_jp_payment_po_3pl_access
    orch_automation_tools.submit_main_excel(driver, self.excel_template, 'Excel Sheet Upload')
  File "C:\Praca\Automation\src\orch_automation_tools.py", line 481, in submit_main_excel
    "//td[contains(text(),'Accepted')]"
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//td[contains(text(),'Accepted')]"}
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)


======================================================================
ERROR [91.441894s]: JP_test_suite.CITPNGJPPaymentTests.PNG Payment PO change to FI 3PL Has Access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Praca\Automation\src\JP_test_suite.py", line 1458, in test_png_jp_payment_po_to_fi_3pl_access
    orch_automation_tools.submit_main_excel(driver, self.excel_template, 'Excel Sheet Upload')
  File "C:\Praca\Automation\src\orch_automation_tools.py", line 481, in submit_main_excel
    "//td[contains(text(),'Accepted')]"
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//td[contains(text(),'Accepted')]"}
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)


----------------------------------------------------------------------
Ran 18 tests in 0:04:39

FAILED
 (Errors=3, Skipped=15)

Generating HTML reports... 
reports\TestResults_CITPNGJPPaymentTests_CITPNGJPImportTests_2019-05-23_13-22-55.html
